from sqlalchemy import Column, Integer,String,BigInteger,TIME,Boolean,ForeignKey
from Model.register import Base

class Scl_Profile(Base):
    __tablename__ = "school_profile"
    owner_id = Column(Integer,ForeignKey("register.id",ondelete="CASCADE"), nullable = False)
    id = Column(Integer, primary_key = True, nullable=False, autoincrement=True)
    inst_name = Column(String, nullable =True)
    postal = Column(String,nullable = True)
    dis = Column(String,nullable = True)
    state = Column(String,nullable = True)
    city = Column(String, nullable = True)
    pin = Column(BigInteger,nullable = True)
    url = Column(String,nullable = True)
    off_email = Column(String,nullable = True)
    off_phone = Column(BigInteger,nullable = True)
    scl_loc = Column(String,nullable = True)
    est_year = Column(BigInteger,nullable = True)
    medium = Column(String,nullable = True)
    nat_affiliation = Column(String,nullable = True)
    scl_level = Column(String,nullable = True)
    gen = Column(String,nullable = True)
    girls = Column(Integer,nullable = True)
    boys = Column(Integer,nullable = True)
    total_stu = Column(Integer,nullable = True)
    teaching_staff= Column(Integer,nullable = True)
    non_teaching = Column(Integer,nullable = True)
    cors_name = Column(String,nullable = True)
    cors_mobile = Column(BigInteger,nullable = True)
    cors_email= Column(String,nullable = True)
    prin_name = Column(String,nullable = True)
    prin_phone = Column(BigInteger,nullable = True)
    prin_email= Column(String,nullable = True)
    prin_mobile = Column(BigInteger,nullable = True)
    reg_govt = Column(String,nullable = True)
    board_name = Column(String,nullable = True) 
    affli_no = Column(BigInteger,nullable = True)
    affili_year = Column(Integer,nullable = True)
    per_temp = Column(String,nullable = True)
    cond = Column(BigInteger,nullable = True)
    minor_sta_cer = Column(String,nullable = True)
    christian = Column(Integer,nullable = True)
    hindu = Column(Integer,nullable = True)
    muslim= Column(Integer,nullable = True)
    others= Column(Integer,nullable = True)
    non_believe= Column(Integer,nullable = True)
    fire= Column(String,nullable = True)
    sanitation= Column(String,nullable = True)
    building= Column(String,nullable = True)
    scl_owned= Column(String,nullable = True)
    trust_name= Column(String,nullable = True)
    registered= Column(String,nullable = True)
    act= Column(String,nullable = True)
    reg_year= Column(Integer,nullable = True)
    reg_no= Column(Integer,nullable = True)
    reg_validity= Column(Integer,nullable = True)
    president_name = Column(String,nullable = True)
    designation= Column(String,nullable = True)
    address= Column(String,nullable = True)
    president_phone= Column(BigInteger,nullable = True)
    president_email= Column(String,nullable = True)
    governing= Column(String,nullable = True)
    members= Column(Integer,nullable = True)
    mem_tenure= Column(Integer,nullable = True)
    EPCC = Column(String,nullable = True)
    EPCC_mem= Column(Integer,nullable = True)
    EPCC_tenure= Column(Integer,nullable = True)
    par_techer= Column(String,nullable = True)
    par_teacher_mem= Column(Integer,nullable = True)
    par_techer_tenure= Column(Integer,nullable = True)
    stud = Column(String,nullable = True)
    stud_mem= Column(Integer,nullable = True)
    stud_tenure= Column(Integer,nullable = True)
    general= Column(String,nullable = True)
    scl_manage_commi= Column(String,nullable = True)
    constitute_commi= Column(String,nullable = True)
    constitute_mem= Column(Integer,nullable = True)
    constitute_tenure= Column(Integer,nullable = True)
    scl_location= Column(String,nullable = True)
    area= Column(String,nullable = True)
    built_area= Column(String,nullable = True)
    play_area= Column(String,nullable = True)
    no_building= Column(Integer,nullable = True)
    provision= Column(String,nullable = True)
    no_staircase= Column(Integer,nullable = True)
    no_lifts= Column(Integer,nullable = True)
    class_room= Column(Integer,nullable = True)
    staff_room= Column(Integer,nullable = True)
    physics_lab= Column(Integer,nullable = True)
    chemistry_lab= Column(Integer,nullable = True)
    bio_lab= Column(Integer,nullable = True)
    math_lab= Column(Integer,nullable = True)
    comp_lab= Column(Integer,nullable = True)
    lang_lab= Column(Integer,nullable = True)
    home_lab= Column(Integer,nullable = True)
    library= Column(Integer,nullable = True)
    auditorium= Column(Integer,nullable = True)
    counselor_room= Column(Integer,nullable = True)
    visitor_parlor= Column(Integer,nullable = True)
    prayer_room= Column(Integer,nullable = True)
    sick_room= Column(Integer,nullable = True)
    canteen= Column(Integer,nullable = True)
    security_room= Column(Integer,nullable = True)
    other_room= Column(Integer,nullable = True)
    staff_toilet= Column(Integer,nullable = True)
    stu_toilet= Column(Integer,nullable = True)
    room= Column(Integer,nullable = True)
    spl_need= Column(String,nullable = True)
    staff_spl_need= Column(String,nullable = True)
    boundary_wall= Column(String,nullable = True)
    wall_status= Column(String,nullable = True)
    cctv= Column(String,nullable = True)
    data_saved= Column(String,nullable = True)
    no_camera= Column(Integer,nullable = True)
    male_guard= Column(String,nullable = True)
    no_male_guard= Column(Integer,nullable = True)
    female_guard= Column(String,nullable = True)
    no_female_guard= Column(String,nullable = True)
    water_facility= Column(String,nullable = True)
    drainage_facility= Column(String,nullable = True)
    midday= Column(String,nullable = True)
    no_bus= Column(Integer,nullable = True)
    gps_camera= Column(Integer,nullable = True)
    lady_attendantor= Column(Integer,nullable = True)
    first_aid= Column(Integer,nullable = True)
    drinking_water= Column(Integer,nullable = True)
    bus_sub_contract= Column(Integer,nullable = True)
    bus_pass= Column(String,nullable = True)
    free_transport= Column(String,nullable = True)
    lib_open= Column(TIME,nullable = True)
    lib_close= Column(TIME,nullable = True)
    no_book= Column(Integer,nullable = True)
    no_magazine= Column(Integer,nullable = True)
    no_newspaper= Column(Integer,nullable = True)
    no_ebook= Column(Integer,nullable = True)
    online_access= Column(String,nullable = True)
    sep_lib= Column(String,nullable = True)
    remedial_teaching= Column(String,nullable = True)
    multimedia1= Column(Boolean ,nullable = True)
    multimedia2= Column(Boolean ,nullable = True)
    multimedia3= Column(Boolean ,nullable = True)
    multimedia4= Column(Boolean ,nullable = True)
    multimedia5= Column(Boolean ,nullable = True)
    prin_per_male= Column(Integer,nullable = True)
    prin_per_female= Column(Integer,nullable = True)
    prin_tem_male= Column(Integer,nullable = True)
    prin_tem_female= Column(Integer,nullable = True)
    vp_per_male= Column(Integer,nullable = True)
    vp_per_female= Column(Integer,nullable = True)
    vp_tem_male= Column(Integer,nullable = True)
    vp_tem_female= Column(Integer,nullable = True)
    pgt_per_male= Column(Integer,nullable = True)
    pgt_per_female= Column(Integer,nullable = True)
    pgt_tem_male= Column(Integer,nullable = True)
    pgt_tem_female= Column(Integer,nullable = True)
    tgt_per_male= Column(Integer,nullable = True)
    tgt_per_female= Column(Integer,nullable = True)
    tgt_tem_male= Column(Integer,nullable = True)
    tgt_tem_female= Column(Integer,nullable = True)
    prt_per_male= Column(Integer,nullable = True)
    prt_per_female= Column(Integer,nullable = True)
    prt_tem_male= Column(Integer,nullable = True)
    prt_tem_female= Column(Integer,nullable = True)
    ntt_per_male= Column(Integer,nullable = True)
    ntt_per_female= Column(Integer,nullable = True)
    ntt_tem_male= Column(Integer,nullable = True)
    ntt_tem_female= Column(Integer,nullable = True)
    untrained_per_male= Column(Integer,nullable = True)
    untrained_per_female= Column(Integer,nullable = True)
    untrained_tem_male= Column(Integer,nullable = True)
    untrained_tem_female= Column(Integer,nullable = True)
    lib_per_male= Column(Integer,nullable = True)
    lib_per_female= Column(Integer,nullable = True)
    lib_tem_male= Column(Integer,nullable = True)
    lib_tem_female= Column(Integer,nullable = True)
    art_per_male= Column(Integer,nullable = True)
    art_per_female= Column(Integer,nullable = True)
    art_tem_male= Column(Integer,nullable = True)
    art_tem_female= Column(Integer,nullable = True)
    counsellor_per_male= Column(Integer,nullable = True)
    counsellor_per_female= Column(Integer,nullable = True)
    counsellor_tem_male= Column(Integer,nullable = True)
    counsellor_tem_female= Column(Integer,nullable = True)
    lit_per_male= Column(Integer,nullable = True)
    lit_per_female= Column(Integer,nullable = True)
    lit_tem_male= Column(Integer,nullable = True)
    lit_tem_female= Column(Integer,nullable = True)
    faith_per_male= Column(Integer,nullable = True)
    faith_per_female= Column(Integer,nullable = True)
    faith_tem_male= Column(Integer,nullable = True)
    faith_tem_female= Column(Integer,nullable = True)
    nurse_per_male= Column(Integer,nullable = True)
    nurse_per_female= Column(Integer,nullable = True)
    nurse_tem_male= Column(Integer,nullable = True)
    nurse_tem_female= Column(Integer,nullable = True)
    pt_per_male= Column(Integer,nullable = True)
    pt_per_female= Column(Integer,nullable = True)
    pt_tem_male= Column(Integer,nullable = True)
    pt_tem_female= Column(Integer,nullable = True)
    off_manager_per= Column(Integer,nullable = True)
    off_manager_tem= Column(Integer,nullable = True)
    off_manager_part= Column(Integer,nullable = True)
    off_asst_per= Column(Integer,nullable = True)
    off_asst_tem= Column(Integer,nullable = True)
    off_asst_part= Column(Integer,nullable = True)
    clerk_per= Column(Integer,nullable = True)
    clerk_tem= Column(Integer,nullable = True)
    clerk_part= Column(Integer,nullable = True)
    lab_per= Column(Integer,nullable = True)
    lab_tem= Column(Integer,nullable = True)
    lab_part= Column(Integer,nullable = True)
    accountant_per= Column(Integer,nullable = True)
    accountant_tem= Column(Integer,nullable = True)
    accountant_part= Column(Integer,nullable = True)
    peon_per= Column(Integer,nullable = True)
    peon_tem= Column(Integer,nullable = True)
    peon_part= Column(Integer,nullable = True)
    other_per= Column(Integer,nullable = True)
    other_tem= Column(Integer,nullable = True)
    other_part= Column(Integer,nullable = True)
    no_curri_act= Column(Integer,nullable = True)
    no_grp= Column(Integer,nullable = True)
    no_community= Column(Integer,nullable = True)
    scl= Column(Integer,nullable = True)
    zonal= Column(Integer,nullable = True)
    dist= Column(Integer,nullable = True)
    stat= Column(Integer,nullable = True)
    national= Column(Integer,nullable = True)
    international= Column(Integer,nullable = True)
    c_scl= Column(Integer,nullable = True)
    c_zonal= Column(Integer,nullable = True)
    c_dist= Column(Integer,nullable = True)
    c_stat= Column(Integer,nullable = True)
    c_national= Column(Integer,nullable = True)
    c_international= Column(Integer,nullable = True)
    inter_scl= Column(Integer,nullable = True)
    inter_zonal= Column(Integer,nullable = True)
    inter_dist= Column(Integer,nullable = True)
    inter_stat= Column(Integer,nullable = True)
    inter_national= Column(Integer,nullable = True)
    inter_international= Column(Integer,nullable = True)
    ac_begin_mon= Column(String,nullable = True)
    ac_end_mon= Column(String,nullable = True)
    working_day_21= Column(Integer,nullable = True)
    working_day_20= Column(Integer,nullable = True)
    working_day_19= Column(Integer,nullable = True)
    hrs_21= Column(Integer,nullable = True)
    hrs_20= Column(Integer,nullable = True)
    hrs_19= Column(Integer,nullable = True)
    instruct_hrs_21= Column(Integer,nullable = True)
    instruct_hrs_20= Column(Integer,nullable = True)
    instruct_hrs_19= Column(Integer,nullable = True)
    non_instruct_hrs_21= Column(Integer,nullable = True)
    non_instruct_hrs_20= Column(Integer,nullable = True)
    non_instruct_hrs_19= Column(Integer,nullable = True)
    holiday_21= Column(Integer,nullable = True)
    holiday_20= Column(Integer,nullable = True)
    holiday_19= Column(Integer,nullable = True)
    sub_teaching_week= Column(Integer,nullable = True)
    moral_week= Column(Integer,nullable = True)
    teaching_duration= Column(Integer,nullable = True)
    hrs_club= Column(Integer,nullable = True)
    scl_tim_sum_from= Column(TIME,nullable = True)
    scl_tim_sum_to= Column(TIME,nullable = True)
    scl_tim_win_from= Column(TIME,nullable = True)
    scl_tim_win_to= Column(TIME,nullable = True)
    shift= Column(String,nullable = True)
    # scholarship = Column(String, nullable = True)

