from sqlalchemy import Column, Integer,String,BigInteger,TIME,Boolean,ForeignKey
from Model.register import Base


class Scl_Profile(Base):
    __tablename__ = "school_profile"
    owner_id = Column(Integer,ForeignKey("register.id",ondelete="CASCADE"), nullable = False)
    id = Column(Integer, primary_key = True, nullable=False, autoincrement=True)
    instituteName = Column(String, nullable =True)
    postal = Column(String,nullable = True)
    district = Column(String,nullable = True)
    state = Column(String,nullable = True)
    city = Column(String, nullable = True)
    pincode = Column(BigInteger,nullable = True)
    url = Column(String,nullable = True)
    officialEmail = Column(String,nullable = True)
    officialPhone = Column(BigInteger,nullable = True)
    schoolLocation = Column(String,nullable = True)
    establishmentYear = Column(BigInteger,nullable = True)
    medium = Column(String,nullable = True)

    natureOfAffiliation = Column(String,nullable = True)
    schoolLevel = Column(String,nullable = True)
    gender = Column(String,nullable = True)
    currentGirls = Column(Integer,nullable = True)
    CurrentBoys = Column(Integer,nullable = True)
    totalStudents = Column(Integer,nullable = True)
    teachingStaff= Column(Integer,nullable = True)
    nonTeachingStaff = Column(Integer,nullable = True)
    correspondentName = Column(String,nullable = True)
    correspondentMobile = Column(BigInteger,nullable = True)
    correspondentEmail= Column(String,nullable = True)

    principalName = Column(String,nullable = True)
    principalPhone = Column(BigInteger,nullable = True)
    principalEmail= Column(String,nullable = True)
    principalMobile = Column(BigInteger,nullable = True)

    instituteRecognizedByGovt = Column(String,nullable = True)
    boardName = Column(String,nullable = True) 
    affiliationNo = Column(BigInteger,nullable = True)
    affiliationYear = Column(Integer,nullable = True)
    affiliationType = Column(String,nullable = True)
    affiliationCondition = Column(BigInteger,nullable = True)
    minorityStatusCertificate = Column(String,nullable = True)
    christian = Column(Integer,nullable = True)
    hindu = Column(Integer,nullable = True)
    muslim= Column(Integer,nullable = True)
    others= Column(Integer,nullable = True)
    nonBeliever= Column(Integer,nullable = True)
    fireSaftyCertificate= Column(String,nullable = True)
    sanitationCertificate= Column(String,nullable = True)
    buildingSaftyCertificate= Column(String,nullable = True)

    schoolOwnedBy= Column(String,nullable = True)
    trustName= Column(String,nullable = True)
    isTrustRegistered= Column(String,nullable = True)
    act= Column(String,nullable = True)
    registrationYear= Column(Integer,nullable = True)
    registrationNo= Column(Integer,nullable = True)
    registrationValidity= Column(Integer,nullable = True)
    presidentName = Column(String,nullable = True)
    presidentDesignation= Column(String,nullable = True)
    presidentAddress= Column(String,nullable = True)
    presidentPhone= Column(BigInteger,nullable = True)
    presidentEmail= Column(String,nullable = True)

    governingBodyOfTrust= Column(String,nullable = True)
    members= Column(Integer,nullable = True)
    tenureMember= Column(Integer,nullable = True)
    epcc = Column(String,nullable = True)
    epccMember= Column(Integer,nullable = True)
    epccTenure= Column(Integer,nullable = True)
    parentTeacherAssociation= Column(String,nullable = True)
    parentTeacherAssociationMember= Column(Integer,nullable = True)
    parentTeacherAssociationTenure= Column(Integer,nullable = True)

    studentAssociation = Column(String,nullable = True)
    studentAssociationMember= Column(Integer,nullable = True)
    studentAssociationTenure= Column(Integer,nullable = True)
    generalComplaintCell= Column(String,nullable = True)
    schoolManagementCommittee= Column(String,nullable = True)
    constitutionCommittee= Column(String,nullable = True)
    constitutionMember= Column(Integer,nullable = True)
    constitutionTenure= Column(Integer,nullable = True)

    schoolBuildingType= Column(String,nullable = True)
    schoolCampusArea= Column(String,nullable = True)
    builtupArea= Column(String,nullable = True)
    playGroundArea= Column(String,nullable = True)
    noOfBuilding= Column(Integer,nullable = True)
    provision= Column(String,nullable = True)
    noOfStaircase= Column(Integer,nullable = True)
    noOfLifts= Column(Integer,nullable = True)

    classRoom= Column(Integer,nullable = True)
    staffRoom= Column(Integer,nullable = True)
    physicsLab= Column(Integer,nullable = True)
    chemistryLab= Column(Integer,nullable = True)
    biologyLab= Column(Integer,nullable = True)
    mathsLab= Column(Integer,nullable = True)
    computerLab= Column(Integer,nullable = True)
    languageLab= Column(Integer,nullable = True)
    homeScienceLab= Column(Integer,nullable = True)
    library= Column(Integer,nullable = True)
    auditorium= Column(Integer,nullable = True)
    counselorRoom= Column(Integer,nullable = True)
    visitorParlor= Column(Integer,nullable = True)
    prayerRoom= Column(Integer,nullable = True)
    sickRoom= Column(Integer,nullable = True)
    canteen= Column(Integer,nullable = True)
    securityRoom= Column(Integer,nullable = True)
    otherRoom= Column(Integer,nullable = True)
    staffToilet= Column(Integer,nullable = True)
    studentToilet= Column(Integer,nullable = True)
    room= Column(Integer,nullable = True)
    splNeeds= Column(String,nullable = True)
    staffSpeciallNeed= Column(String,nullable = True)

    boundaryWall= Column(String,nullable = True)
    wallStatus= Column(String,nullable = True)
    cctv= Column(String,nullable = True)
    dataSaved= Column(String,nullable = True)
    noOfCamera= Column(Integer,nullable = True)
    maleGuard= Column(String,nullable = True)
    noOfMaleGuard= Column(Integer,nullable = True)
    femaleGuard= Column(String,nullable = True)
    noOfFemaleGuard= Column(String,nullable = True)
    waterFacility= Column(String,nullable = True)
    drainageFacility= Column(String,nullable = True)

    midday= Column(String,nullable = True)
    noOfOwnedBus= Column(Integer,nullable = True)
    gpsCamera= Column(Integer,nullable = True)
    ladyAttendantor= Column(Integer,nullable = True)
    firstAid= Column(Integer,nullable = True)
    drinkingWater= Column(Integer,nullable = True)
    subContractedBus= Column(Integer,nullable = True)
    busPass= Column(String,nullable = True)
    freeTransport= Column(String,nullable = True)

    libraryOpen= Column(TIME,nullable = True)
    libraryClose= Column(TIME,nullable = True)
    noOfLibraryBook= Column(Integer,nullable = True)
    noOfLibraryMagazine= Column(Integer,nullable = True)
    noOfDailies= Column(Integer,nullable = True)
    noOfeBook= Column(Integer,nullable = True)
    onlineAccess= Column(String,nullable = True)
    separateLibrary= Column(String,nullable = True)
    remedialTeaching= Column(String,nullable = True)
    multimedia1= Column(Boolean ,nullable = True)
    multimedia2= Column(Boolean ,nullable = True)
    multimedia3= Column(Boolean ,nullable = True)
    multimedia4= Column(Boolean ,nullable = True)
    multimedia5= Column(Boolean ,nullable = True)

    permanentMalePrincipal= Column(Integer,nullable = True)
    permanentFemalePrincipal= Column(Integer,nullable = True)
    temporaryMalePrincipal= Column(Integer,nullable = True)
    temporaryFemalePrincipal= Column(Integer,nullable = True)
    permanentMaleVP= Column(Integer,nullable = True)
    permanentFemaleVP= Column(Integer,nullable = True)
    temporaryMaleVP= Column(Integer,nullable = True)
    temporaryFemaleVP= Column(Integer,nullable = True)
    permanentMalePGT= Column(Integer,nullable = True)
    permanentFemalePGT= Column(Integer,nullable = True)
    temporaryMalePGT= Column(Integer,nullable = True)
    temporaryFemalePGT= Column(Integer,nullable = True)
    permanentMaleTGT= Column(Integer,nullable = True)
    permanentFemaleTGT= Column(Integer,nullable = True)
    temporaryMaleTGT= Column(Integer,nullable = True)
    temporaryFemaleTGT= Column(Integer,nullable = True)
    permanentMalePRT= Column(Integer,nullable = True)
    permanentFemalePRT= Column(Integer,nullable = True)
    temporaryMalePRT= Column(Integer,nullable = True)
    temporaryFemalePRT= Column(Integer,nullable = True)
    permanentMaleNTT= Column(Integer,nullable = True)
    permanentFemaleNTT= Column(Integer,nullable = True)
    temporaryMaleNTT= Column(Integer,nullable = True)
    temporaryFemaleNTT= Column(Integer,nullable = True)
    permanentUntrainedMale= Column(Integer,nullable = True)
    permanentUntrainedFemale= Column(Integer,nullable = True)
    temporaryUntrainedMale= Column(Integer,nullable = True)
    temporaryUntrainedFemale= Column(Integer,nullable = True)
    permanentMaleLibrarian= Column(Integer,nullable = True)
    permanentFemaleLibrarian= Column(Integer,nullable = True)
    temporaryMaleLibrarian= Column(Integer,nullable = True)
    temporaryFemaleLibrarian= Column(Integer,nullable = True)
    permanentMaleArts= Column(Integer,nullable = True)
    permanentFemaleArts= Column(Integer,nullable = True)
    temporaryMaleArts= Column(Integer,nullable = True)
    temporaryFemaleArts= Column(Integer,nullable = True)
    permanentMaleCounsellor= Column(Integer,nullable = True)
    permanentFemaleCounsellor= Column(Integer,nullable = True)
    temporaryMaleCounsellor= Column(Integer,nullable = True)
    temporaryFemaleCounsellor= Column(Integer,nullable = True)
    permanentMaleLiteracy= Column(Integer,nullable = True)
    permanentFemaleLiteracy= Column(Integer,nullable = True)
    temporaryMaleliteracy= Column(Integer,nullable = True)
    temporaryFemaleliteracy= Column(Integer,nullable = True)
    permanentMaleMinister= Column(Integer,nullable = True)
    permanentFemaleMinister= Column(Integer,nullable = True)
    temporaryMaleMinister= Column(Integer,nullable = True)
    temporaryFemaleMinister= Column(Integer,nullable = True)
    permanentMaleNurse= Column(Integer,nullable = True)
    permanentFemaleNurse= Column(Integer,nullable = True)
    temporaryMaleNurse= Column(Integer,nullable = True)
    temporaryFemaleNurse= Column(Integer,nullable = True)
    permanentMalePT= Column(Integer,nullable = True)
    permanentFemalePT= Column(Integer,nullable = True)
    temporaryMalePT= Column(Integer,nullable = True)
    temporaryFemalePT= Column(Integer,nullable = True)

    permanentOfficeManager= Column(Integer,nullable = True)
    temporaryOfficeManager= Column(Integer,nullable = True)
    partTimeOfficeManager= Column(Integer,nullable = True)
    permanentOfficeAsst= Column(Integer,nullable = True)
    temporaryOfficeAsst= Column(Integer,nullable = True)
    partTimeOfficeAsst= Column(Integer,nullable = True)
    permanentClerk= Column(Integer,nullable = True)
    temporaryClerk= Column(Integer,nullable = True)
    partTimeClerk= Column(Integer,nullable = True)
    permanentLabAttendant= Column(Integer,nullable = True)
    temporaryLabAttendant= Column(Integer,nullable = True)
    partTimeLabAttendant= Column(Integer,nullable = True)
    permanentAccountant= Column(Integer,nullable = True)
    temporaryAccountant= Column(Integer,nullable = True)
    partTimeAccountant= Column(Integer,nullable = True)
    permanentPeon= Column(Integer,nullable = True)
    temporaryPeon= Column(Integer,nullable = True)
    partTimePeon= Column(Integer,nullable = True)
    permanentOthers= Column(Integer,nullable = True)
    temporaryOthers= Column(Integer,nullable = True)
    partTimeOthers= Column(Integer,nullable = True)

    noOfCarricularActivity= Column(Integer,nullable = True)
    noOfGrps= Column(Integer,nullable = True)
    noOfCommunity= Column(Integer,nullable = True)
    noOfSportsAtSchool= Column(Integer,nullable = True)
    noOfSportsAtZonal= Column(Integer,nullable = True)
    noOfSportsAtDist= Column(Integer,nullable = True)
    noOfSportsAtState= Column(Integer,nullable = True)
    noOfSportsAtNational= Column(Integer,nullable = True)
    noOfSportsAtInternational= Column(Integer,nullable = True)
    noOfCompetitionAtSchool= Column(Integer,nullable = True)
    noOfCompetitionAtZonal= Column(Integer,nullable = True)
    noOfCompetitionAtDist= Column(Integer,nullable = True)
    noOfCompetitionAtState= Column(Integer,nullable = True)
    noOfCompetitionAtNational= Column(Integer,nullable = True)
    noOfCompetitionAtInternational= Column(Integer,nullable = True)
    noOfSclProgramsAtSchool= Column(Integer,nullable = True)
    noOfSclProgramsAtZonal= Column(Integer,nullable = True)
    noOfSclProgramsAtDist= Column(Integer,nullable = True)
    noOfSclProgramsAtState= Column(Integer,nullable = True)
    noOfSclProgramsAtNational= Column(Integer,nullable = True)
    noOfSclProgramsAtInternational= Column(Integer,nullable = True)

    academicYearBeginingMonth= Column(String,nullable = True)
    academicYearEndingMonth= Column(String,nullable = True)
    workingDay2021= Column(Integer,nullable = True)
    workingDay2020= Column(Integer,nullable = True)
    workingDay2019= Column(Integer,nullable = True)
    hrsOfAcademic2021= Column(Integer,nullable = True)
    hrsOfAcademic2020= Column(Integer,nullable = True)
    hrsOfAcademic2019= Column(Integer,nullable = True)
    instructionalHrs2021= Column(Integer,nullable = True)
    instructionalHrs2020= Column(Integer,nullable = True)
    instructionalHrs2019= Column(Integer,nullable = True)
    nonInstructuionalWorkingday2021= Column(Integer,nullable = True)
    nonInstructuionalWorkingday2020= Column(Integer,nullable = True)
    nonInstructuionalWorkingday2019= Column(Integer,nullable = True)
    holiday2021= Column(Integer,nullable = True)
    holiday2020= Column(Integer,nullable = True)
    holiday2019= Column(Integer,nullable = True)
    
    noOfSubTeachingPeriod= Column(Integer,nullable = True)
    noOfMoralTeachingPeriod= Column(Integer,nullable = True)
    teachingDuration= Column(Integer,nullable = True)
    noOfClubHrs= Column(Integer,nullable = True)
    fromTimeInSummer= Column(TIME,nullable = True)
    toTimeInSummer= Column(TIME,nullable = True)
    fromTimeInWinter= Column(TIME,nullable = True)
    toTimeInWinter= Column(TIME,nullable = True)
    shift= Column(String,nullable = True)
    # scholarship = Column(String, nullable = True)

