"""scholarship

Revision ID: 131840a3dfb9
Revises: 
Create Date: 2022-09-08 12:59:14.165865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131840a3dfb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scl_profile', sa.Column('scholarship_name0', sa.String(), nullable=True))
    op.add_column('scl_profile', sa.Column('boy0', sa.Integer(), nullable=True))
    op.add_column('scl_profile', sa.Column('girl0', sa.Integer(), nullable=True))
    op.add_column('scl_profile', sa.Column('by_govt0', sa.String(), nullable=True))
    op.add_column('scl_profile', sa.Column('by_private0', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scl_profile', 'by_private0')
    op.drop_column('scl_profile', 'by_govt0')
    op.drop_column('scl_profile', 'girl0')
    op.drop_column('scl_profile', 'boy0')
    op.drop_column('scl_profile', 'scholarship_name0')
    # ### end Alembic commands ###
