"""addScholar

Revision ID: 50a868ce8d35
Revises: 
Create Date: 2022-09-13 10:48:48.986669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a868ce8d35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scl_profile', sa.Column('scholarship', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scl_profile', 'scholarship')
    # ### end Alembic commands ###
