"""principalchanged

Revision ID: 38eb80204b18
Revises: 85b6eb3b7713
Create Date: 2022-09-28 12:28:23.310511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38eb80204b18'
down_revision = '85b6eb3b7713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('permanentMalePrincipal', sa.Integer(), nullable=True))
    op.add_column('school_profile', sa.Column('permanentFemalePrincipal', sa.Integer(), nullable=True))
    op.drop_column('school_profile', 'permanentMalePricipal')
    op.drop_column('school_profile', 'permanentFemalePricipal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('permanentFemalePricipal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('school_profile', sa.Column('permanentMalePricipal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('school_profile', 'permanentFemalePrincipal')
    op.drop_column('school_profile', 'permanentMalePrincipal')
    # ### end Alembic commands ###
